apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: web
        app: demo
        env: staging
    spec:
      containers:
      - name: web
        image: stealthizer/k8s-tester
        ports:
        - containerPort: 5000
